# Generated by Django 3.1.3 on 2020-11-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdescription',
            name='photo',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
